export const stateCodeNo = {
    "01": "Jammu and Kashmir",
    "02": "Himachal Pradesh",
    "03": "Punjab",
    "04": "Chandigarh",
    "05": "Uttarakhand",
    "06": "Haryana",
    "07": "Delhi",
    "08": "Rajasthan",
    "09": "Uttar Pradesh",
    "10": "Bihar",
    "11": "Sikkim",
    "12": "Arunachal Pradesh",
    "13": "Nagaland",
    "14": "Manipur",
    "15": "Mizoram",
    "16": "Tripura",
    "17": "Meghalaya",
    "18": "Assam",
    "19": "West Bengal",
    "20": "Jharkhand",
    "21": "Odisha",
    "22": "Chhattisgarh",
    "23": "Madhya Pradesh",
    "24": "Gujarat",
    "25": "Daman & Diu",
    "26": "Dadra and Nagar Haveli",
    "27": "Maharashtra",
    "29": "Karnataka",
    "30": "Goa",
    "31": "Lakshadweep",
    "32": "Kerala",
    "33": "Tamil Nadu",
    "34": "Pondicherry",
    "35": "Andaman & Nicobar Islands",
    "36": "Telangana",
    "37": "Andhra Pradesh",
    "38": "Ladakh",
    "98": "IMPORT (Not Registered in India)"
}


export enum StateCode {
    JammuAndKashmir = "01",
    HimachalPradesh = "02",
    Punjab = "03",
    Chandigarh = "04",
    Uttarakhand = "05",
    Haryana = "06",
    Delhi = "07",
    Rajasthan = "08",
    UttarPradesh = "09",
    Bihar = "10",
    Sikkim = "11",
    ArunachalPradesh = "12",
    Nagaland = "13",
    Manipur = "14",
    Mizoram = "15",
    Tripura = "16",
    Meghalaya = "17",
    Assam = "18",
    WestBengal = "19",
    Jharkhand = "20",
    Odisha = "21",
    Chhattisgarh = "22",
    MadhyaPradesh = "23",
    Gujarat = "24",
    DamanAndDiu = "25",
    DadraAndNagarHaveli = "26",
    Maharashtra = "27",
    Karnataka = "29",
    Goa = "30",
    Lakshadweep = "31",
    Kerala = "32",
    TamilNadu = "33",
    Pondicherry = "34",
    AndamanAndNicobarIslands = "35",
    Telangana = "36",
    AndhraPradesh = "37",
    Ladakh = "38",
    ImportNotRegisteredInIndia = "98"
}
