import type { CreateCorporateKycPayload } from "@root/schema";

export const defaultCorporateKycForm: CreateCorporateKycPayload = {
  entityName: "",
  dateOfCommencementOfBusiness: "",
  countryOfIncorporation: "",
  panCopyFileUrl: "",
  entityConstitutionType: undefined,
  otherConstitutionType: "",
  dateOfIncorporation: "",
  placeOfIncorporation: "",
  panNumber: "",
  cinOrRegistrationNumber: "",
  correspondenceFullAddress: "",
  correspondenceLine1: "",
  correspondenceLine2: "",
  correspondenceCity: "",
  correspondenceDistrict: "",
  correspondencePinCode: "",
  correspondenceState: "",
  balanceSheetCopyUrl: "",
  certificateOfIncorporationUrl: "",
  memorandumCopyUrl: "",
  boardResolutionCopyUrl: "",
  gstCopyUrl: "",
  clientMasterHoldingCopyUrl: "",
  annualIncome: "",
  shareHoldingPatternCopyUrl: "",
  certificateOfCommencementOfBizUrl: "",
  articlesOfAssociationUrl: "",
  gstNumber: "",
  directorsListCopyUrl: "",
  powerOfAttorneyCopyUrl: "",
  documentsType: "",
  fatcaApplicable: false,
  fatcaEntityName: "",
  fatcaCountryOfIncorporation: "",
  fatcaEntityType: undefined,
  fatcaClassification: "",
  giin: "",
  taxResidencyOfEntity: "",
  declarationByAuthorisedSignatory: false,
  bankAccounts: [],
  dematAccounts: [],
  directors: [],
  promoters: [],
  authorisedSignatories: [],
};
