import { Text, View } from "@react-pdf/renderer";
import React from "react";
import { tw } from "../MdPdf";
import TextList from "../elements/TextList";

function Page22() {
  return (
    <View style={tw(`w-[90%]  px-4  mx-auto `)}>
      <View
        style={{
          flexDirection: "column",
          alignItems: "flex-start",
          justifyContent: "flex-start",
          gap: 10,
          marginTop: 15,
        }}
      >
        <TextList count="35.">
          The stock broker shall send daily margin statements to the clients.
          Daily Margin statement should include, interalia, details of
          collateral deposited, collateral utilized and collateral status
          (available balance/due from client) with break up in terms of cash,
          Fixed Deposit Receipts (FDRs), Bank Guarantee and securities.
        </TextList>
        <TextList count="36.">
          The Client shall ensure that it has the required legal capacity to,
          and is authorized to, enter into the relationship with stock broker
          and is capable of performing his obligations and undertakings
          hereunder. All actions required to be taken to ensure compliance of
          all the transactions, which the Client may enter into shall be
          completed by the Client prior to such transaction being entered into.
        </TextList>
        <Text style={tw(`font-bold uppercase text-xs`)}>
          ELECTRONIC CONTRACT NOTES (ECN)
        </Text>
        <TextList count="37.">
          In case, client opts to receive the contract note in electronic form,
          he shall provide an appropriate e-mail id to the stock broker. The
          client shall communicate to the stock broker any change in the
          email-id through a physical letter. If the client has opted for
          internet trading, the request for change of email id may be made
          through the secured access by way of client specific user id and
          password.
        </TextList>
        <TextList count="38.">
          The stock broker shall ensure that all ECNs sent through the e-mail
          shall be digitally signed, encrypted, non-tamper able and in
          compliance with the provisions of the IT Act, 2000. In case, ECN is
          sent through e-mail as an attachment, the attached file shall also be
          secured with the digital signature, encrypted and non-tamperable.
        </TextList>
        <TextList count="39.">
          The client shall note that non-receipt of bounced mail notification by
          the stock broker shall amount to delivery of the contract note at the
          e-mail ID of the client.
        </TextList>
        <TextList count="40.">
          The stock broker shall retain ECN and acknowledgement of the e-mail in
          a soft and non-tamperable form in the manner prescribed by the
          exchange in compliance with the provisions of the IT Act, 2000 and as
          per the extant rules/regulations/circulars/guidelines issued by
          SEBI/Stock Exchanges from time to time. The proof of delivery i.e.,
          log report generated by the system at the time of sending the contract
          notes shall be maintained by the stock broker for the specified period
          under the extant regulations of SEBI/stock exchanges. The log report
          shall provide the details of the contract notes that are not delivered
          to the client/e-mails rejected or bounced back. The stock broker shall
          take all possible steps to ensure receipt of notification of bounced
          mails by him at all times within the stipulated time period under the
          extant regulations of SEBI/stock exchanges.
        </TextList>
        <TextList count="41.">
          The stock broker shall continue to send contract notes in the physical
          mode to such clients who do not opt to receive the contract notes in
          the electronic form. Wherever the ECNs have not been delivered to the
          client or has been rejected (bouncing of mails) by the e-mail ID of
          the client, the stock broker shall send a physical contract note to
          the client within the stipulated time under the extant regulations of
          SEBI/stock exchanges and maintain the proof of delivery of such
          physical contract notes.
        </TextList>
        <TextList count="42.">
          In addition to the e-mail communication of the ECNs to the client, the
          stock broker shall simultaneously publish the ECN on his designated
          web-site, if any, in a secured way and enable relevant access to the
          clients and for this purpose, shall allot a unique user name and
          password to the client, with an option to the client to save the
          contract note electronically and/or take a print out of the same.
        </TextList>
      </View>
    </View>
  );
}

export default Page22;
