import { geistSans } from "@/global/font/font";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import React from "react";
import Client from "./client";
import "react-json-view-lite/dist/index.css";
import "./globals.css";
export const revalidate = 0;
export const metadata: Metadata = {
  title: "MeraDhan CRM - Portal",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <NextTopLoader color="#003569" />
        <Client>{children}</Client>
      </body>
    </html>
  );
}
