import type { DataBaseSchema } from "@core/database/database";
export const fullCustomerProfileSelect: DataBaseSchema.CustomerProfileDataModelSelect =
  {
    aadhaarCard: true,
    bankAccounts: true,
    currentAddress: true,
    dematAccounts: true,
    panCard: true,
    permanentAddress: true,
    personalInformation: true,
    userName: true,
    firstName: true,
    lastName: true,
    updatedAt: true,
    userType: true,
    avatar: true,
    createdBy: true,
    kycStatus: true,
    kraStatus: true,
    middleName: true,
    emailAddress: true,
    phoneNo: true,
    gender: true,
    whatsAppNo: true,
    VerifiedBy: true,
    verifyDate: true,
    id: true,
    isAPep: true,
    allowSEBITerms: true,
    isAFatcaCustomer: true,

    riskProfile: true,
    createdAt: true,

    utility: {
      select: {
        accountStatus: true,
        id: true,
        isEmailVerified: true,
        isPhoneVerified: true,
        signinWith: true,
        termsAccepted: true,
        lastLogin: true,
        whatsAppNotificationAllow: true,
        relationshipManager: true,
      },
    },
  };

export const basicProfileInfoSelect: DataBaseSchema.CustomerProfileDataModelSelect =
  {
    id: true,
    firstName: true,
    middleName: true,
    lastName: true,
    userType: true,
    emailAddress: true,
    phoneNo: true,
    whatsAppNo: true,
    kycStatus: true,
    createdAt: true,
    userName: true,
    gender: true,
    avatar: true,
    utility: {
      select: {
        accountStatus: true,
        termsAccepted: true,
        whatsAppNotificationAllow: true,
        isEmailVerified: true,
        isPhoneVerified: true,
        lastLogin: true,
        signinWith: true,
      },
    },
  };
