import { geistMono, geistSans } from "@/global/font/font";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import Client from "./client";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hello Team",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        <Client>{children}</Client>
      </body>
    </html>
  );
}
